repos:
    # pre-commit-hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json

    # flake8
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: __init__
        args:
            - "--max-line-length=120"

    # black
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.11
      args:
        - "--line-length=120"

    # mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy


    # isort
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args:
        - "--line-length=120"
